/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
    // By default, Docusaurus generates a sidebar from the docs folder structure
    skillsSidebar: [
        {
            type: 'doc',
            id: 'intro',
            label: 'À lire en premier'
        },
        {
            type: 'doc',
            id: 'alternance/entreprise',
            label: 'Mon entreprise d’alternance',
        },
        {
            type: 'doc',
            id: 'formation/but-info',
            label: 'Ma formation',
        },
        {
            type: 'doc',
            id: 'skills/c1c2c3/projet-global',
            label: 'Réaliser, optimiser et administrer',
        },
        {
            type: 'doc',
            id: 'skills/c4/c4',
            label: 'Gérer des données de l\'information',
        }
    ],
    /*
    introductionSidebar: [
        {
            type: 'autogenerated',
            dirName: 'introduction'
        }
    ],
    remerciementSidebar: [
        {
            type: 'autogenerated',
            dirName: 'remerciement',
        },
    ],
    annexesSidebar: [
        {
            type: 'autogenerated',
            dirName: 'annexes',
        },
    ],*/

};

export default sidebars;
