/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
    // By default, Docusaurus generates a sidebar from the docs folder structure
    skillsSidebar: [
        {
            type: 'doc',
            id: 'intro',
            label: 'À lire en premier'
        },
        {
            type: 'doc',
            id: 'alternance/entreprise',
            label: 'Mon entreprise d’alternance',
        },
        {
            type: 'doc',
            id: 'formation/but-info',
            label: 'Ma formation',
        },
        {
            type: 'category',
            label: 'Projets',
            items: [
                {
                    type: 'doc',
                    id: 'skills/projects/projet-tut',
                    label: 'Projet tutoré : Suivi de ligne AI',
                },
                {
                    type: 'doc',
                    id: 'skills/projects/projet-plateforme',
                    label: 'Projet Plateforme pédagogique',
                },
            
            ]
        },
        {
            type: 'doc',
            id: 'skills/c1c2c3/projet-global',
            label: 'C1, C2 et C3 - Réaliser, optimiser et administrer',
        },
        {
            type: 'doc',
            id: 'skills/c4/c4',
            label: 'C4 - Gérer des données de l\'information',
        },
        {
            type: 'doc',
            id: 'skills/c5/c5',
            label: 'C5 - Conduire un projet',
        },
        {
            type: 'doc',
            id: 'skills/c6/c6',
            label: 'C6 - Collaborer au sein d\'une équipe informatique',
        },
        {
            type: 'doc',
            id: 'bilan/skills-goal',
            label: 'Récapitulatif des compétences & traces',
        },
        {
            type: 'doc',
            id: 'remerciement/thank',
            label: 'Remerciements',
        },
        
    ],
    agileSidebar: [
        {
            type: 'doc',
            id: 'agile-niort/douceur',
            label: 'La douceur est-elle un avantage dans ce monde de brutes ?',
        },
        {
            type: 'doc',
            id: 'agile-niort/cartographier',
            label: 'Cartographier pour mieux avancer',
        },

    ],
    /*
    introductionSidebar: [
        {
            type: 'autogenerated',
            dirName: 'introduction'
        }
    ],
    remerciementSidebar: [
        {
            type: 'autogenerated',
            dirName: 'remerciement',
        },
    ],
    annexesSidebar: [
        {
            type: 'autogenerated',
            dirName: 'annexes',
        },
    ],*/

};

export default sidebars;
